name: cargo-readme

on:
  push
  # push:
    # branches:
    #   - main
    #   - develop
    #   - feat/readme/cargo-readme-workflow

jobs:
  generate-readmes:
    runs-on: ubuntu-latest

    steps:
      - run: echo hello