name: cargo-readme

on:
  workflow_call:
    inputs:
      REPO:
        type: string
        required: false
        default: "./"
  # push:
  # branches:
  #   - main
  #   - develop
  #   - feat/readme/cargo-readme-workflow

jobs:
  generate-readmes:
    runs-on: ubuntu-latest

    steps:
      - name: Install cargo-readme
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-readme

      # - uses: actions/checkout@v2

      - name: Setup tmate session if build and test run failed
        uses: mxschmitt/action-tmate@v3

      # - name: Generate README for crate hdk
      #   run: cd crates/hdk && cargo readme
